spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    driver-class-name: com.mysql.jdbc.Driver
##    type: org.apache.commons.dbcp2.BasicDataSource
